sudo: required
dist: trusty

services:
  - docker

language: go

go:
  - 1.7

before_install:
  - sudo apt-get update
  - sudo apt-get install -y docker-engine liblxc1 lxc-dev lxc
  - sudo apt-get install -y qemu

install:
  - make bootstrap

script:
  - make test

notifications:
  email:
    recipients:
      - kiran.mova@cloudbyte.com
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d885a0beef16020c3878

